services:
  telepirate:
    depends_on:
      - surrealdb
      - telegram-api
    container_name: telepirate
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile-telepirate
    environment:
      - TELOXIDE_TOKEN=${TELOXIDE_TOKEN}
    env_file: ./.env
    restart: always
    stop_grace_period: 1s

  surrealdb:
    container_name: surrealdb
    build:
      dockerfile: ./dockerfiles/Dockerfile-surrealdb
    volumes:
      - ./dbdata:/persistence
    restart: always
    stop_grace_period: 1s

  telegram-api:
    container_name: telegram-api
    build:
      dockerfile: ./dockerfiles/Dockerfile-telegram-api
    environment:
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
    env_file: ./.env
    restart: always
    stop_grace_period: 1s

networks:
  piranet:
    name: piranet
    driver: bridge
