FROM rust:1.80-bookworm

RUN apt update && apt upgrade -y && apt install -y git curl llvm cmake binutils clang qemu-user musl-tools libssl-dev pkg-config build-essential protobuf-compiler
RUN git clone https://github.com/surrealdb/surrealdb.git /surrealdb
WORKDIR /surrealdb
RUN mkdir /persistence
# Release commit of v1.5.3
RUN git checkout fbd0a24a6761fc5ba50a822b6fc9c0b6170bed37
RUN cargo install --path .

ENTRYPOINT surreal start --log info --user root --pass root file:/persistence
