FROM rust:1.80-bookworm

RUN apt update && apt upgrade -y && apt install -y make git zlib1g-dev libssl-dev gperf cmake clang libc++-dev libc++abi-dev
RUN git clone --depth 1 --recursive https://github.com/tdlib/telegram-bot-api.git /telegram-bot-api

WORKDIR /telegram-bot-api
RUN rm -vrf build && mkdir build && cd build && CXXFLAGS="-stdlib=libc++" CC=/usr/bin/clang CXX=/usr/bin/clang++ cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=.. .. && cmake --build . -j $(nproc) --target install

ENTRYPOINT bin/telegram-bot-api --local
