FROM rust:1.82-bookworm AS builder

RUN apt update && apt upgrade -y && apt install -y --no-install-recommends gcc pkg-config openssl libssl-dev
WORKDIR /app
COPY . .
RUN cargo build

FROM debian:bookworm-slim
COPY --from=builder /app/target/debug/telepirate /usr/bin/telepirate
RUN apt update && apt upgrade -y && apt install -y --no-install-recommends python3 pip ca-certificates ffmpeg
RUN pip install --break-system-packages -U "yt-dlp[default]"

ENTRYPOINT telepirate
