FROM rust:1.82-bookworm

RUN apt update && apt upgrade -y && apt install -y --no-install-recommends gcc pkg-config openssl libssl-dev python3 pip ca-certificates ffmpeg
RUN pip install --break-system-packages -U "yt-dlp[default]"
WORKDIR /app
COPY . .
RUN cargo build

ENTRYPOINT /app/target/debug/telepirate
