FROM rust:1.80-bookworm

RUN apt update && apt upgrade -y && apt install -y --no-install-recommends git yt-dlp ffmpeg gcc pkg-config openssl libssl-dev python3 pip
RUN pip install --break-system-packages -U "yt-dlp[default]"
WORKDIR /telepirate
COPY . /telepirate

RUN cargo install --path /telepirate

ENTRYPOINT telepirate
